# Generated by Django 3.2.5 on 2023-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20231026_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='url',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='pictures/'),
        ),
    ]
