# Generated by Django 3.2.5 on 2023-10-27 22:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20231027_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitepicturemodel',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
